version: '3.1'

services:
  slowloris:
    build: .
    depends_on: 
      - nginx
    command: [ "python", "./slowloris.py", "nginx", "-s", "10000" ]

  nginx:
    image: nginx
    ports:
     - "8080:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
