version: '3'
services:    
  # nginx:
  #   image: nginx
  #   ports:
  #   - "80:80"
  #   volumes:
  #   - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
  #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  apache:
    image: httpd:2.4
    ports:
    - "80:80"
    volumes:
    - ./apache/example.conf:/etc/apache2/sites-enabled/example.conf

  web:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    # ports:
    #  - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000

  postgres:
    image: postgres